spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.173.129:3306/house-item-place?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.173.129
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-wait: 3000
        max-idle: 10
        min-idle: 5
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase_mysql.xml
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml  # Mapper文件的位置
#  typeAliasesPackage: com.example.demo.entity  # 实体类的包路径



server:
  port: 8999
knife4j:
  enable: true